### ISSUE TITLE
Feedback/Improvement - Colors

### ISSUE THREAD

**Issue by newnix** [K0stad1n/bash-learner#2]
I see that you're directly `#include`-ing "colors.c", which in turn is comprised of several functions that only serve to call `printf(3)` with the appropriate escape sequence. Instead, you may want to rename this `colors.h` and replace all the functions with macros containing the appropriate escape sequence. So you'd have something like:
```c
#define RED L"\033[1;31m"
```
and then using it like so:
```c
printf("%s%s%s\n", RED, "This text is red!", RESET);
```

While not important for this application, it will reduce your call stack depth for printing text and generally allow for more  flexible use of colors.

**Comment by emilrl-gh** [comment]
Added colors.h thank you for your feedback !
