### ISSUE TITLE
Feedback/Improvement - I/O Streams

### ISSUE THREAD

**Issue by newnix** [K0stad1n/bash-learner#4]
Consider using `fprintf(3);`, this will allow you to easily direct output to one of several I/O streams, such as `stdout` and `stderr`. Doing so will also allow you to more easily distinguish between things the user's being prompted for, things that are erroneous, and things being logged elsewhere.

For example:
```c
#include <err.h>
#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "color.h"

/* Error opening the record file */
if (fp == NULL) {
  fprintf(stderr, "%s: %s!\n", __progname, strerror(errno));
}

/* Recording progress */
fprintf(fp, "%s\n", "Made it to task 3");

/* Prompting to continue */
fprintf(stdout, "%s%s%s [%sY%s/%sn%s]\n> ", BOLDYELLOW, "Continue?", RESET, BRIGHTGREEN, RESET, RED, RESET);
```

**Comment by emilrl-gh** [comment]
When you say prompting to continue do you mean that I should prompt the user when I find a checkpoint if he wants to continue or something else ?

**Comment by newnix** [comment]
It's just an example usage of using `fprintf(3)` to create dialog, but having that dialog somewhere can be beneficial. For example, maybe if you can't create or read the checkpoint file, allow the user to decide if they want to continue without saving their progress.

**Comment by K0stad1n** [comment]
When I try adding the prompting to continue after the first line of error opening the record file. 
I get a segmentation fault.
