### ISSUE TITLE
Binary file for macOS doesn't work.

### ISSUE THREAD

**Issue by ftpd** [K0stad1n/bash-learner#6]
~/Downloads
❯ ll
.rw-r--r--@ 25k f 10 Aug 22:38 bash-learner-macos
~/Downloads
❯ chmod +x bash-learner-macos
~/Downloads
❯ ./bash-learner-macos
sh: checkforupdate.sh: No such file or directory
zsh: segmentation fault  ./bash-learner-macos

**Comment by emilrl-gh** [comment]
Hi thanks for posting this issue ! Did you try to re run the program ? Did you ask the program to not create a file or to create a file ?

**Comment by ftpd** [comment]
I wasn't able to reach this point. The binary simply crashes just after downloading, because there is no 'checkupdate.sh' file in the current directory, and it's required here: https://github.com/K0stad1n/bash-learner/blob/master/bash-learner.c#L24-L26

**Comment by emilrl-gh** [comment]
Ok I will fix that thanks very much

**Comment by emilrl-gh** [comment]
Please try again by downloading the new file.

**Comment by ftpd** [comment]
It works now, but it's not a solution. Binary should not depend on some shell script.
But it's your project, so if you're happy with this, feel free to close the issue.

**Comment by ftpd** [comment]
Btw. README points to hardcoded 1.1.0 version. It makes more sense to point to <latest>.
